pub const SCHEMAS: &[(&str, &str)] = &[
    ("v1", include_str!("../../../../migrations/0001_init.sql")),
    ("v2", include_str!("../../../../migrations/0002_split_uploads.sql")),
    ("v3", include_str!("../../../../migrations/0003_chapter_byte_ranges.sql")),
    ("v4", include_str!("../../../../migrations/0004_data_assets.sql")),
    ("v5", include_str!("../../../../migrations/0005_chapters_data_asset_fk.sql")),
    ("v6", include_str!("../../../../migrations/0006_transformation_novels_data_asset_fk.sql")),
    ("v7", include_str!("../../../../migrations/0007_uploads_word_count.sql")),
    ("v8", include_str!("../../../../migrations/0008_tn_default_columns.sql")),
    ("v9", include_str!("../../../../migrations/0009_batches.sql")),
    ("v10", include_str!("../../../../migrations/0010_tc_batch_columns.sql")),
    ("0011_workflow_results", include_str!("../../../../migrations/0011_workflow_results.sql")),
    ("0012_batches_tn_cascade", include_str!("../../../../migrations/0012_batches_tn_cascade.sql")),
    ("0013_workflow_result_chapters_cascade", include_str!("../../../../migrations/0013_workflow_result_chapters_cascade.sql")),
    ("0014_builtin_prompt_double_braces", include_str!("../../../../migrations/0014_builtin_prompt_double_braces.sql")),
    ("v15", include_str!("../../../../migrations/0015_chapter_body.sql")),
    ("v16", include_str!("../../../../migrations/0016_model_archive.sql")),
    ("v17", include_str!("../../../../migrations/0017_prompt_archive.sql")),
];
